### ISSUE TITLE
Pig hooves

### ISSUE THREAD

**Issue by alacielx** [Faithful-Resource-Pack/Faithful-Bedrock-64x#2]
![pig](https://user-images.githubusercontent.com/62450706/185818344-be2d99e3-d4ac-4923-843c-42a1eca77962.png)
![pig](https://user-images.githubusercontent.com/62450706/185818436-4948c5ee-a45f-49aa-8054-c9a752c29d5e.png)
I think the pig texture is supposed to have cloven hooves with 2 toes, but it looks like it has 8 toes per foot. I made a small edit of my own just wanted to share my discovery

**Comment by HARYA301** [comment]
Hey! Unfortunately this isn't a bug but a texture change that we don't accept here on Github.
However, join us [here](https://discord.gg/sN9YRQbBv7) to submit textures changes like so.
