### ISSUE TITLE
When is it exiting beta?

### ISSUE THREAD

**Issue by ShaunRoselt** [Faithful-Resource-Pack/Faithful-Bedrock-64x#6]
The last release was in 2022 and that was Beta 5: https://github.com/Faithful-Resource-Pack/Faithful-Bedrock-64x/releases/tag/beta-5

When is there going to be a new [GitHub release](https://github.com/Faithful-Resource-Pack/Faithful-Bedrock-64x/releases) and when is it exiting Beta?

**Comment by RobertRR11** [comment]
We don't release on GitHub anymore. Check our website for the latest release https://faithfulpack.net/faithful64x/R4
